arguments = test_ppo_init_state.py $(train_seed) $(validate_seed) $(test_seed) $(maturity_threshold)
executable = shared/kick2goal/run.sh


log = job_$(train_seed)_$(maturity_threshold).log
error = job_$(train_seed)_$(maturity_threshold).err
output = job_$(train_seed)_$(maturity_threshold).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = shared/

request_cpus = 9
request_memory = 16GB
request_disk = 10GB

queue train_seed,validate_seed,test_seed,maturity_threshold from shared/kick2goal/seeds5.txt