container_image = docker://joszhong/kick2goal:init
universe = container

arguments = $(train_seed) $(test_seed)
executable = run_docker.sh


log = job_$(train_seed).log
error = job_$(train_seed).err
output = job_$(train_seed).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = ./

request_cpus = 9
request_memory = 16GB
request_disk = 1GB

queue train_seed,test_seed from seeds.txt